import os
import numpy as np
from pathlib import Path
from natsort import natsorted


template = """; automatically generated by generate_mpb_ctl_supercell.f90
;MATERIAL
 (define-param eps    11.560000000000000      ) ; the dielectric constant of the material of the rods
 (define diel (make dielectric (epsilon eps)))
 
;GEOMETRY OF LATTICE BASIS
 (define-param rad   0.18900000000000000       ) ;radius of the cylinder
; Generating square lattice:
 (set! geometry-lattice (make lattice (size    {Lx}        {Ly}       no-size)  ; size of the primitive vectors
                         (basis1 1. 0. )
                         (basis1 0. 1. )))

;points of the irreducible Brillouin zone
 (define Gamma (vector3 0 0 0))  ; Gamma point
 (define M (vector3  0.5 0.5 0))  ; M point
 (define X (vector3  0.5 0 0))  ; X point
 (set! num-bands          500  ) ; number of bands
 ;(set! k-points (list Gamma X M Gamma)) ; path in the K space
 (set! k-points (list Gamma X)) ; path in the K space
 (set! k-points (interpolate            5  k-points)) ; interpolation
 (set! resolution          32  )
 (set! tolerance   9.99999975E-05  )
 
; define function to pass from cartesian to lattice 
 (define (c->l . args) (cartesian->lattice (apply vector3 args)))  ;conversion function from cartesian to lattice
 
;Generating the rods in the supercell 
 (set! geometry 
    (list
{cylinders}
 ))  ; end of geometry list
 
;tell MPB to run TM bands only
 (run-tm)
"""


def get_positions(file_path,samples:int=5):
    
    data = []
    centers = []

    with open(file_path,"r") as f: 
        lines = f.read().splitlines() 
        i=0
        index = 1
        num_samples = int(lines[index].split()[0])

        while num_samples>0 and i < 300:
            try:
                num_samples = int(lines[index].split()[0])
                old_index = index
                index += num_samples+1
                li = (lines[old_index+1:index])
                centers = np.array([list(map(float, item.split())) for item in li])
                data += [{
                    "centers":centers,
                    "Lx":float(lines[old_index].split()[1]),
                    "Ly":float(lines[old_index].split()[2]),
                    "points":float(lines[old_index].split()[0]),
                }]
                i+=1
            except:
                num_samples = 0
        return data[:samples]
        

def create_ctl_from_positions(output_dir:any=None, dir_path:any=None,samples:int=5):
    for l,file in enumerate(natsorted(os.listdir(dir_path))):
        print(Path(file).stem)
        positions = get_positions(os.path.join(dir_path,file),samples=samples) 
        for k,item in enumerate(positions):
            cylinders = []
            for center in item["centers"]:
                x, y = center
                cylinders.append(
                    "         (make cylinder\n"
                    "            (material diel)\n"
                    f"            (center (c->l   {x:.17f}  {y:.17f}     0. )) \n"
                    "            (radius rad)\n"
                    "            (height infinity)\n"
                    "         )\n"
                )
            all_cyls = "".join(cylinders)
            out_path = os.path.join(output_dir if output_dir else dir_path,"CTL_Files",Path(file).stem, f"{Path(file).stem}_Lx_{item['Lx']}_Ly_{item['Ly']}_N_{item['points']}_rods_sample_{k+1}.ctl")
            os.makedirs(os.path.dirname(out_path), exist_ok=True)
            with open(out_path, 'w', newline='\n') as out:
                out.write(template.format(cylinders=all_cyls,Lx=item["Lx"],Ly=item["Ly"]))


create_ctl_from_positions(dir_path=rf"H:\phd stuff\tidy3d\Notebooks\2D SHU Project\20250623 MPB Bands\Luis Data\SHU 2D point patterns (N=200)",
                          samples=5)




