import os

input_path = r"H:\phd stuff\tidy3d\Notebooks\2D SHU Project\20250623 MPB Bands\Luis Data\bands_SHU_chi_0.37_eps_11p56_N10000\chi_0.37_positions.txt"
output_dir = os.path.dirname(input_path)
os.makedirs(output_dir, exist_ok=True)

template = """; automatically generated by generate_mpb_ctl_supercell.f90
;MATERIAL
 (define-param eps    11.560000000000000      ) ; the dielectric constant of the material of the rods
 (define diel (make dielectric (epsilon eps)))
 
;GEOMETRY OF LATTICE BASIS
 (define-param rad   0.18900000000000000       ) ;radius of the cylinder
; Generating square lattice:
 (set! geometry-lattice (make lattice (size    100.029991        100.029991       no-size)  ; size of the primitive vectors
                         (basis1 1. 0. )
                         (basis1 0. 1. )))

;points of the irreducible Brillouin zone
 (define Gamma (vector3 0 0 0))  ; Gamma point
 (define M (vector3  0.5 0.5 0))  ; M point
 (define X (vector3  0.5 0 0))  ; X point
 (set! num-bands          1500  ) ; number of bands
 ;(set! k-points (list Gamma X M Gamma)) ; path in the K space
 (set! k-points (list Gamma)) ; path in the K space
 ;(set! k-points (interpolate            25  k-points)) ; interpolation
 (set! resolution          8  )
 (set! tolerance   9.99999975E-05  )
 
; define function to pass from cartesian to lattice 
 (define (c->l . args) (cartesian->lattice (apply vector3 args)))  ;conversion function from cartesian to lattice
 
;Generating the rods in the supercell 
 (set! geometry 
    (list
{cylinders}
 ))  ; end of geometry list
 
;tell MPB to run TM bands only
 (run-tm)
"""

def parse_line(line):
    line = line.split('#', 1)[0].strip()
    if not line:
        return None
    parts = [p for p in line.replace(',', ' ').split() if p]
    if len(parts) < 2:
        return None
    try:
        x = float(parts[0])
        y = float(parts[1])
    except ValueError:
        return None
    return x, y

with open(input_path, 'r') as f:
    lines = f.readlines()

cylinders = []
for line in lines:
    parsed = parse_line(line)
    if not parsed:
        continue
    x, y = parsed
    cylinders.append(
        "         (make cylinder\n"
        "            (material diel)\n"
        f"            (center (c->l   {x:.17f}  {y:.17f}     0. )) \n"
        "            (radius rad)\n"
        "            (height infinity)\n"
        "         )\n"
    )

all_cyls = "".join(cylinders)
out_path = os.path.join(output_dir, "mpb_all_rods.ctl")
with open(out_path, 'w', newline='\n') as out:
    out.write(template.format(cylinders=all_cyls))

print("Done — wrote:", out_path)